version: '3'
services:
  auth:
    container_name: bingo-auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:3000
    env_file:
      - ./auth/.env
    volumes:
      - ./usr/:/app
    links:
      - postgresql
  postgresql:
    container_name: postgresql_b1ngo
    image: postgres:latest
    restart: always
    env_file:
      - database.env
    ports:
      - "5432:5432"
  salas:
    container_name: bingo-salas
    build:
      context: ./salas
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5001:3001
    env_file:
      - ./salas/.env
    volumes:
      - ./salas:/app
    links:
      - postgresql
